---
apiVersion: v2
name: nginx-plus-dos-ingress
type: application
version: 1.1.1
appVersion: "2.4.1"
dependencies:
  - name: nginx-ingress
    version: 0.15.1
    repository: https://helm.nginx.com/stable
