nginx-ingress:
  controller:
    nginxplus: true
    #kind: deployment
    #replicaCount: 1
    appprotect:
      enable: true
    appprotectdos:
      enable: true
      maxWorkers: 1
      maxDaemons: 1
      memory: 32
    ingressClass: nginx-plus-nap-dos-ingress
    config:
      proxy-protocol: true
      real-ip-header: proxy_protocol
      set-real-ip-from: 0.0.0.0/0
    #enableCustomResources: true
    enablePreviewPolicies: true
    enableSnippets: true
    enableTLSPassthrough: true
    enableLatencyMetrics: true
    healthStatus: true
    nginxStatus:
      #enable: true
      port: 9000
      allowCidrs: 0.0.0.0/0
    service:
      name: nginx-plus-nap-dos-ingress
      #type: LoadBalancer
    image:
      repository:
      tag:
  #prometheus:
    #create: true
